services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    privileged: true
    volumes:
      - ./ssh_authorized_keys:/build/airootfs/root/.ssh/authorized_keys
      - ./build/airootfs/usr/local/bin/aria2-wrapper:/usr/local/bin/aria2-wrapper:ro
      - ./build:/build
      - ./iso:/iso
