services:
  builder:
    image: archlinux:latest
    command: ["/usr/local/bin/entrypoint.sh"]
    privileged: true
    volumes:
      - ./build/airootfs/usr/local/bin/aria2-wrapper:/usr/local/bin/aria2-wrapper:ro
      - ./scripts/entrypoint.sh:/usr/local/bin/entrypoint.sh
      - ./build:/build
      - ./iso:/iso
      # TODO : mount stuff we may want: bake in key/token from .env ()
      #   - getntext evoked by scripts/entrypoint.sh
      #     - provide base the following:
      #- ssh_auth_volume:/build/airootfs/root/.ssh/authorized_keys
      #- gh_token_volume:/build/airootfs/root/ithub_token
      # ts_token_volume:/build/airootfs/root/ts_token_volume
    # env_file:
    #   - .env
# volumes:
#   ssh_auth_volume:
#   gh_token_volume:

