services:
  builder:
    image: archlinux:latest
    command: ["/usr/local/bin/build.sh"]
    #privileged: true
    volumes:
      - ./build:/build
      - ./build/airootfs/usr/local/bin/aria2-wrapper:/usr/local/bin/aria2-wrapper:ro
      - ./iso:/iso
      - ./scripts/build.sh:/usr/local/bin/build.sh
    environment:
      BUILD_DIR: "/build"
      OUT_DIR: "/iso"
      WORK_DIR: "/build/work"
